tls:
  stores:
    default: {}

  certificates:
    - certFile: /certs/fullchain.pem
      keyFile: /certs/privkey.pem

http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

    strip-wazuh:
      stripPrefix:
        prefixes:
          - "/wazuh"

  routers:
    redirect:
      rule: "HostRegexp(`{host:.+}`)"
      entryPoints: ["web"]
      middlewares: ["redirect-to-https"]
      service: "noop@internal"

    whoami:
      rule: "Host(`whoami.soc.local`)"
      entryPoints: ["websecure"]
      tls: {}
      service: "whoami"

    wazuh_dashboard:
      rule: "Host(`soc.local`) && PathPrefix(`/wazuh`)"
      entryPoints: ["websecure"]
      tls: {}
      middlewares:
        - "strip-wazuh"
      service: "wazuh_dashboard"

  services:
    whoami:
      loadBalancer:
        servers:
          - url: "http://wazuh_whoami:80"

    wazuh_dashboard:
      loadBalancer:
        servers:
          - url: "http://wazuh_wazuh_dashboard:5600"
